apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mysdatabase;

    USE mysdatabase;
    
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_name VARCHAR(50),
      creation_date TIMESTAMP
    );

    INSERT INTO users (user_name, creation_date) VALUES
    ('daniel', '2024-07-29 13:24:58'),
    ('test', '2024-07-29 13:28:47');
