version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
    - "3307:3307"
    volumes:
    - .db/init.sql:/docker-entypoint-initdb.d/init.sql
    - db_data:/var/lib/mysql

volumes:
  db_data: